### ISSUE TITLE
Layout measurement override of element ItemsRepeater should not return NaN values as its DesiredSize

### ISSUE THREAD

**Issue by Valkirie** [iNKORE-NET/UI.WPF.Modern#72]
Similar to https://github.com/Kinnara/ModernWpf/issues/350, I get the above exception when I insert an item at index 0 to the collection that the ItemsRepeater is binded to.

```
Layout measurement override of element 'iNKORE.UI.WPF.Modern.Controls.ItemsRepeater' should not return NaN values as its DesiredSize.   at System.Windows.UIElement.Measure(Size availableSize)
   at iNKORE.UI.WPF.Controls.SimpleStackPanel.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by NotYoojun** [comment]
Anyone has any ideas how to fix this?

**Comment by Valkirie** [comment]
I'm afraid no.

**Comment by NotYoojun** [comment]
Too bad, no one has any ideas on how to fix this.
If anyone's got a solution, please feel free to comment and I'll reopen!
