### ISSUE TITLE
[Bug] Gallery在点击Menus-AppBarButton时崩溃

### ISSUE THREAD

**Issue by Hellobaka** [iNKORE-NET/UI.WPF.Modern#96]
**Describe the bug**
Gallery在点击Menus-AppBarButton以及CommandBarFlyout时崩溃

**To Reproduce**
1. 从微软商店获取Gallery
2. 切换左侧导航至Menus并点击AppBarButton

**Expected behavior**
不发生崩溃

**Screenshots**
![image](https://github.com/user-attachments/assets/772e19e9-bd24-4fd2-a8e0-e7eee2764cc4)

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2
 - Gallery Version 0.9.30.0

**Additional context**
```
Application: iNKORE.UI.WPF.Modern.Gallery.exe
CoreCLR Version: 6.0.3324.36610
.NET Version: 6.0.33
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Windows.Markup.XamlParseException: 设置属性“iNKORE.UI.WPF.Modern.Controls.FontIcon.Glyph”时引发了异常。
 ---> System.ArgumentException: “iNKORE.UI.WPF.Modern.Common.IconKeys.FontIconData”不是属性“Glyph”的有效值。
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.ResourceDictionary.CreateObject(KeyRecord key)
   at System.Windows.ResourceDictionary.OnGettingValue(Object key, Object& value, Boolean& canCache)
   at System.Windows.ResourceDictionary.GetValueWithoutLock(Object key, Boolean& canCache)
   at System.Windows.ResourceDictionary.GetValue(Object key, Boolean& canCache)
   at System.Windows.ResourceDictionary.get_Item(Object key)
   at iNKORE.UI.WPF.Modern.Gallery.ControlPages.CommandBarFlyoutPage..ctor() in E:\Yujun Products\iNKORE.UI.WPF.Modern\source\iNKORE.UI.WPF.Modern.Gallery\ControlPages\CommandBarFlyoutPage.xaml.cs:line 27
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   --- End of inner exception stack trace ---
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at iNKORE.UI.WPF.Modern.Controls.Frame.Navigate(Type sourcePageType) in E:\Yujun Products\iNKORE.UI.WPF.Modern\source\Inkore.UI.WPF.Modern\Controls\Frame.cs:line 238
   at iNKORE.UI.WPF.Modern.Gallery.ItemPage.OnNavigatedTo(NavigationEventArgs e) in E:\Yujun Products\iNKORE.UI.WPF.Modern\source\iNKORE.UI.WPF.Modern.Gallery\ItemPage.xaml.cs:line 147
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at iNKORE.UI.WPF.Modern.Gallery.App.Main()
```

**Comment by NotYoojun** [comment]
看看从最新的仓库源码编译之后还有没有这个问题？我这可以了：

![image](https://github.com/user-attachments/assets/ffd2bdd9-917b-4c51-9f8b-97a04a2b8618)

**Comment by Hellobaka** [comment]
OK最新仓库没有问题

**Comment by NotYoojun** [comment]
# 🎉 iNKORE.UI.WPF.Modern 0.10.0 has released!
More features and bug fixes available (with this issue fixed)
Check out: https://github.com/iNKORE-NET/UI.WPF.Modern/releases/tag/v0.10.0
